#RandomCoords: Need Help Setting Up? See the Wiki! http://randomwiki.jolbol1.com/
#Teleport Settings
MaxCoordinate: 5000
MinCoordinate: 0
CooldownTime: 5
CooldownApplys:
 - Command
 - Warps
InvulTime: 10
TimeBeforeTeleport: 5
TimeBeforeApplys:
 - Command
 - Warps
 - Signs
MaxAttempts: 20
RandomOrg: false
StopOnMove: true
StopOnCombat: true
ChunkLoader: false
Sound: ENTITY_ENDERDRAGON_FLAP
Effect: ENDER_SIGNAL
BannedWorlds:
 - world_the_end

#Safety Checks
CheckingRadius: 100
Factions: false
GriefPrevention: false
AvoidPlayers: false
Towny: false
WorldBorder: false
WorldGuard: false
RedProtect: false
Kingdoms: false
VanillaBorder: true
SkyBlock: false
Residence: false
Regions:
 - example

#On Join Features
OnJoin: false
OnJoinCommand: none
BonusChest: false
BonusChestItems:
 - Essentials:Dtools

# Teleport Method, Can be random or warps
Command: random
All: random
Others: random
Portals: random
Signs: random
Join: random

#Economy Settings
CommandCost: 0
PortalCost: 0

#Warp Settings
WarpCrossWorld: true

#Limiter Settings
UpdateAlert: true
Limit: 0
LimiterApplys:
 - Command
 - Warps
Metrics: true
CircleRadiusDefault: false
CircleRadiusWorlds:
  - example
debug: false
UpdateMessage: true
OnJoinWorlds:
 - example
Experimental: true





